#index:
#    path: /
#    controller: App\Controller\DefaultController::index

guide_michelin_accueil:
  path: /accueil
  controller: App\Controller\GuideController::accueil

guide_michelin_menu:
  path: /menu
  controller: App\Controller\GuideController::menu

guide_michelin_voir:
  path: /resto/voir/{id}
  controller: App\Controller\GuideController::voir

guide_michelin_restos:
  path: /menu/restos
  controller: App\Controller\GuideController::restos